# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
-  
  env:
  - CGO_ENABLED=0
  main: ./
  goos:
  - linux
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
#release:
#  draft: true
changelog:
  skip: true
